### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aduragbemi1992** [malina-dva/RNA-seq-Differential-expression-analysis#1]
when i tried reading in the text file using my data, it brought in the error below

Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed

**Comment by malina-dva** [comment]
Hi Adurag,

It seems you have duplicated gene names in your raw.names.
You will have to remove the duplicated entries and try again.

Best Regards,

Malina

**Comment by Aduragbemi1992** [comment]
oh thanks. I discovered that the problem existed because the count value for some genes were not differentially expressed and as such the value all through was Zero.

However, after resolving this problem I encountered another problem when I tried to run the Dseq and it reads:

error in deseqdataset(se, design = design, ignorerank) : some values in assay are not integers

However, I discovered that if I rounded the count values to a whole number the error will be solved. So my question is this, is it a good practice to round up the values of a RNA-SEq data to a whole number to avoid this error or is there any other explanation for this?

Attached to this is the RNA-Seq file.

Anticipating your response.
[result.txt](https://github.com/malina-dva/RNA-seq-Differential-expression-analysis/files/5924524/result.txt)

**Comment by malina-dva** [comment]
Hi Adurag,

"oh thanks. I discovered that the problem existed because the count value for some genes were not differentially expressed and as such the value all through was Zero."
There is no way to know if genes are deferentially expressed or not before doing the analyses. A value of zero in some condition doesn't mean that these genes are not deferentially expressed relative to another condition.
"However, I discovered that if I rounded the count values to a whole number the error will be solved. So my question is this, is it a good practice to round up the values of a RNA-SEq data to a whole number to avoid this error or is there any other explanation for this?"
I strongly advise against doing anything to the data manually. I guess that for some reason you got RPKM values in the count matrix or your counts are normalized in some other way. You need the RAW counts (without any normalization applied on them) to the analyses. I have also stated the latter clearly in the tutorial.
Please read the explanation for each part of the R code I have supplied in the tutorial (don't just run the code ;)). Also read a few papers regarding general analyses of RNA-seq data, and the documentation of the DESEQ2 package. It will save you a lot of time in the future.
Best regards,
Malina

**Comment by Aduragbemi1992** [comment]
Hi Malina,

First, i would like to appreciate your response to my queries.

Secondly, I want to correct the notion you earlier had that I didn't consult much material before delving into the analysis. I have personally lost count on the number of videos and materials I have looked up for this. Admittedly, this my first time and the current project am working on demands I do this analysis.

Furthermore, I just discovered that the count values I download from the database was for transcript and not genes and also discovered that the count values for transcript and gene are different.

Finally in response to your comment, is it possible or right to say that if the count values for a gene across all biological replicate and conditions is zero then such a gene can be said to not be differentially expressed and as such we could exclude them from our Deseq2 analysis?

Once more I appreciate the time you expend in responding to my queries.

Thanks

**Comment by malina-dva** [comment]
Hi Adurag,

You can include genes that have zero counts across all replicates in the data analyses. That shouldn't cause any troubles because DESEQ2 will simply not consider these genes during the normalization step. If you have noticed I have more than 20 thousand genes in the count matrix. A lot of them have zero values across all conditions.
Have a look at "5. Data normalization and generation of dissimilarity tree" explanation.

Best regards,

Malina

**Comment by Aduragbemi1992** [comment]
Thanks so much.
